### PR TITLE
Created Obstacle: 54603ce89bbfa

### PR DESCRIPTION
**Pull request by kragniz**

### CODE REVIEW

**Comment by RichiH** [comment]
Grabbing one PR at random to reply to.

The point of the PR workflow is that someone else OKs the change before
merging.

If we merge our own PRs, that either means we defeat the point or that this
workflow does not work for this project/phase.

Richard

Sent by mobile; excuse my brevity.

**Comment by kragniz** [comment]
You're correct, this workflow doesn't really suit the current phase of the mapping project. However, the online editor tooling will only create pull requests, so this is the closest equivalent of pushing to master without having to set up a local development environment. As the maps become more fully formed, we can increase the scrutiny of reviews.

**Comment by RichiH** [comment]
Ah, I didn't know that. In that case, this does seem to make "sense" for
now.

Thanks,
Richard

Sent by mobile; excuse my brevity.

**Comment by kragniz** [comment]
Definitely "sense" in inverted commas :)

**Pull request merged**
